#!/bin/bash
brew update
brew upgrade
brew tap homebrew/versions
brew tap phinze/homebrew-cask

brew install curl
brew install ctags
brew install ack
brew install bash
brew install brew-cask
brew install git
brew install hub
# brew link jpeg libpng
# brew install imagemagick
# brew install imagesnap
# sudo ln -s /usr/local/bin/imagesnap /usr/bin/
brew install pv
brew install ssh-copy-id
brew install vim --override-system-vi
brew install wget --enable-iri
brew install tree
brew install gibo
brew install dnsmasq
brew install gawk
brew install redis
brew install z


# brew cask install google-chrome 
# brew cask install charles 
# brew cask install mou 
# brew cask install dropbox 
# brew cask install evernote 
# brew cask install f-lux 
# brew cask install iterm2 
# brew cask install textexpander  
# brew cask install macvim 
# brew cask install vlc 
# brew cask install onepassword 
# brew cask install the-unarchiver 
# brew cask install kaleidoscope 
# brew cask install skype
# brew cask install macupdate-desktop
# brew cask install growlnotify
# brew cask install xtrafinder



brew cleanup
